cs5774b/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('studentswap/', include('studentswap.urls')),
    path('users/', include('users.urls')),


]

studentswap/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [

    path('home/', views.home, name='home'),
    path('buy/items/<int:productid>/', views.productinfo, name='product_detail'), #product detail
    path('buy/items/', views.buyitem, name="buyitem"), #listitemsbycategory
    path('buy/items/all/', views.buy, name="buy"), #listallitems
    path('sell/', views.sell, name="sell"),  #addingitem
    path('searchresults/', views.searchresults, name="searchresults"),
    path('deleteconfirmation/<int:productid>/',views.deleteconfirmation,name="deleteconfirmation"),  #delete confirmation
    path('deleteitem/<int:productid>/',views.delete,name="delete"),   #actual deletion
    path('edititem/<int:productid>/',views.edit,name="edit"),#requesting edit form
    path('editingitem/<int:productid>/',views.savechanges,name="saveedit"),   #saving edited changes
    path('getsubcategories/', views.getsubcategories ,name='get_subcategories'),
    path('filter/', views.filter, name='filtered'),
    path('comment/<int:productid>/<str:username>/', views.addcomment, name='comment'), #add comment
    path('deletecomment/<int:commentid>/', views.deletecomment, name='deletecomment'),  # delete comment
    path('savecomment/<int:commentid>/', views.savecomment, name='savecomment'),  #editing and updating comment


]

users/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='users'

urlpatterns = [

    # path('home/', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('profile/<str:username>', views.profile, name='profile_detail'),  # profile detail
    path('editprofile/<str:username>', views.editprofile, name='profile_edit'),  # get edit form for editing profile details
    path('saveprofile/<str:username>', views.saveprofile, name='saveprofilechanges'),  # saving profile edit details
    path('loggedin/', views.login_user, name="login"),  # login
    path('logout/', views.logout_user, name="logout"),  # logout
    path('wishlist/delete/<int:productid>/', views.wishlistdelete, name="wishlistdelete"),
    path('dashboard/<str:username>', views.dashboard, name="dashboard"),  # user dashboard
    path('home/feed', views.homeactivityfeed, name='homefeed'), #home page showing activity feed for logged in users
    path('wishlist/<int:productid>/<str:username>',views.wishlist, name="wishlist"), #to add item to wishlist
    path('wishlist/<str:username>',views.wishlistpage, name="wishlistpage"),  #to go to wishlist page

]

studentswap/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.


class Item(models.Model):
    itemname=models.CharField(max_length=200)
    price=models.DecimalField(max_digits=10, decimal_places=2)
    description=models.TextField()
    category=models.CharField(max_length=40)
    subcategory=models.CharField(max_length=40)
    imageurl=models.CharField(max_length=200)
    imagealt= models.CharField(max_length=200)
    date_posted=models.DateTimeField(auto_now_add=True)
    # boolean value to keep a track of the user's listings
    is_sold = models.BooleanField(default=False)
    user=models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.itemname

    def get_absolute_url(self):
        return reverse('product_detail', args=[self.id])


# user login data
# regular_user={"username":"Mahita", "password": "regular"}
# admin_user={"username":"Admin", "password": "admin@23"}

studentswap/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from .models import Item, User
from actions.models import Action
from comments.models import Comment
from django.http import JsonResponse
from django.db.models import Q
from django.http import HttpResponse


import random

# Create your views here.

# home view
def home(request):
    return render(request, "studentswap/index.html")

def buy(request):
    itemList = Item.objects.all().order_by('-date_posted')
    return render(request, "studentswap/product/buy.html", {"productlist": itemList})


#list view
def buyitem(request):
    itemList=Item.objects.all().order_by('-date_posted')
    listbycategory=[]
    itemcategory=request.GET.get('category', None)
    if itemcategory is not None:
        for item in itemList:
            if item.category.strip() == itemcategory.strip():
                listbycategory.append(item)
        return render(request, "studentswap/product/buy.html", {"productlist": listbycategory})
    else:
        return render(request, "studentswap/product/buy.html", {"productlist": itemList})



#add view- form to fill in details
def sell(request):
    if request.method=="POST":
        category, subcategory = request.POST.get('subcategoryfilters').split("-")
        name = request.POST.get('itemname')
        price = request.POST.get('price')
        desc = request.POST.get('desc')
        category = category
        subcategory = subcategory
        is_listing=True
        user=User.objects.get(username=request.session.get("username"))

        # assigning default images to categories,subcategories as the application right now doesn't have scope for the user to upload their pictures.
        # all pictures taken from unsplash.com
        if category=="Furniture" :
            if subcategory=='Living Room Furniture':
                imageurl="images/furniture/phillip-goldsberry-fZuleEfeA1Q-unsplash.jpg"
            elif subcategory=='Dining Room Furniture':
                imageurl="images/furniture/samantha-gades-XDaa1RPb6n8-unsplash.jpg"
            elif subcategory=='Bedroom Furniture':
                imageurl="images/furniture/christopher-jolly-GqbU78bdJFM-unsplash.jpg"
            elif subcategory=='Home Office Furniture':
                imageurl="images/furniture/gian-paolo-aliatis-6AWuKs10_M4-unsplash.jpg"
            elif subcategory=='Other':
                imageurl="images/furniture/di_an_h-g_8MrEZAvyE-unsplash.jpg"

        elif category=="Electronic devices":
            if subcategory=='Computer & Accessories':
                imageurl="images/electronic-devices/clement-helardot-95YRwf6CNw8-unsplash.jpg"
            elif subcategory=='Mobile devices & Accessories':
                imageurl="/images/electronic-devices/charlesdeluvio-GXNo-OJynTQ-unsplash.jpg"
            elif subcategory=='Home Appliances':
                imageurl="images/electronic-devices/louis-hansel-ktVKZRYUP4Y-unsplash.jpg"
            elif subcategory=='Audio & Music':
                imageurl="images/electronic-devices/caleb-woods-VVuRLhyTmXM-unsplash.jpg"
            elif subcategory=='Other':
                imageurl="images/electronic-devices/photo-1496181133206-80ce9b88a853.avif"

        elif category=="Home Accessories":
            if subcategory=='Lighting':
                imageurl="images/home accessories/sincerely-media-VDPauwJ_sHo-unsplash.jpg"
            elif subcategory=='Bedding & Linens':
                imageurl="images/home accessories/susan-wilkinson-9I4gTSe3_Po-unsplash.jpg"
            elif subcategory=='Bathroom Accessories':
                imageurl="images/home accessories/curology-cI_LU-uAkcE-unsplash.jpg"
            elif subcategory=='Kitchen Accessories':
                imageurl="images/home accessories/annie-spratt-QOBHnWEg-mk-unsplash.jpg"
            elif subcategory == 'Desk Accessories':
                imageurl = "images/home accessories/freddie-marriage-vSchPA-YA_A-unsplash.jpg"

            elif subcategory=='Other':
                imageurl="images/home accessories/patrick-tomasso-1NTFSnV-KLs-unsplash.jpg"

        elif category == "Books":
            if subcategory=='Textbooks':
                imageurl = "images/books/Structure-and-Interpretation.jpg"
            elif subcategory == 'Notebooks':
                    imageurl = "images/books/Structure-and-Interpretation.jpg"
            elif subcategory == 'Study guides':
                    imageurl = "images/books/Structure-and-Interpretation.jpg"
            elif subcategory == 'Interview Prep':
                    imageurl = "images/books/Structure-and-Interpretation.jpg"
            elif subcategory == 'Other':
                    imageurl = "images/books/Structure-and-Interpretation.jpg"

        elif category == "Kitchenware":
            if subcategory=='Cookware':
                imageurl="images/kitchenware/cooker-king-AOVtEuU9UGc-unsplash.jpg"
            elif subcategory=='Cutlery':
                imageurl="images/kitchenware/anna-kumpan-e8SpIvBceJw-unsplash.jpg"
            elif subcategory=='Kitchen Tools & Utensils':
                imageurl="images/kitchenware/becca-tapert-A_L2xNKgENg-unsplash.jpg"
            elif subcategory=='Kitchen Appliances':
                imageurl="images/kitchenware/alexandre-boucey-IZF51fI0p5w-unsplash.jpg"
            elif subcategory=='Other':
                imageurl="images/kitchenware/cooker-king-zEgp30gYpKk-unsplash.jpg"

        else:
            imageurl='images/miscellaneous/daniel-norris-ZN_86cZrSN0-unsplash.jpg'


        newitem = Item(itemname=name, price=price, description=desc, category=category, subcategory=subcategory,imageurl=imageurl,imagealt=name,user=user,is_sold=is_listing)
        newitem.save()
        #log the action
        action=Action(user=user, verb=f"sold an item -{name} ", target=newitem)
        action.save()
        messages.add_message(request, messages.SUCCESS, "You successfully sold the item %s !" % newitem.itemname)
        return redirect("product_detail", productid=newitem.id)
    else:
        return render(request, "studentswap/product/sell.html",)


# displaying search results based on sample keywords entered by user
def searchresults(request):
    searchresultlist = []
    if request.method=='GET':
        keyword=request.GET.get('searchitems','')
        itemList = Item.objects.all().order_by('-date_posted')
        for item in itemList:
                    if (keyword in ["electronics","computers","devices"]) and item.category == "Electronic devices":
                        searchresultlist.append(item)
                    elif (keyword in ["furniture","bed","table"]) and item.category == "Furniture":
                        searchresultlist.append(item)
                    elif (keyword in ["books","textbooks"]) and item.category == "Books":
                        searchresultlist.append(item)
                    elif (keyword in ["kitchen","cutlery","utensils"]) and item.category == "Kitchenware":
                        searchresultlist.append(item)
                    elif (keyword in ["lights","desk accessories"]) and item.category == "Home Accessories":
                        searchresultlist.append(item)
        return render(request, "studentswap/product/searchresults.html", {"productlist": searchresultlist})



# detail view - if the user sees the product detail, add it to recently viewed list
def productinfo(request,productid):
    itemList = Item.objects.all().order_by('-date_posted')
    comments=Comment.objects.filter(item=productid).order_by('-datecommented')
    for item in itemList:
        if item.id==productid:
            item.save()
            break
    return render(request, "studentswap/product/product.html", {"item": item, 'comments':comments})


#
# # edit view- edit view renders the form where the user can make changes
def edit(request,productid):
    itemList = Item.objects.all()
    for item in itemList:
        if(productid==item.id):
            return render(request,"studentswap/product/editlisting.html",{"item": item})
#
#
#savechanges view actually saves the changes once the form is submitted
def savechanges(request,productid):
    itemList = Item.objects.all()
    category, subcategory = request.POST.get('subcategoryfilters').split("-")
    category = category
    subcategory = subcategory
    print( category, subcategory)
    #logging the user action
    user = User.objects.get(username=request.session.get("username"))


    for item in itemList:
        if(productid==item.id):

            if request.POST.get('desc')!=item.description:
                action = Action(user=user, verb=f"edited the item's description to '{ request.POST.get('desc')}'", target=item)
                action.save()
            item.itemname=request.POST.get('itemname')
            if request.POST.get('itemname')!=item.itemname:
                action = Action(user=user, verb=f"edited the item's name to '{request.POST.get('itemname')}'", target=item)
                action.save()
            item.description=request.POST.get('desc')
            item.price=request.POST.get('price')
            item.category=category
            item.subcategory=subcategory
            item.save()
            break
    messages.add_message(request, messages.INFO, "You successfully edited the item %s !" % item.itemname) #success msg
    return redirect("product_detail", productid=item.id)


# delete views- for confirming the deletion and actually deleting it
def deleteconfirmation(request,productid):
    return render(request, "studentswap/product/deleteconfirmation.html",{"productid":productid})

# search for the item using it's id and delete it from the database
def delete(request,productid):
    itemList = Item.objects.all()
    # logging the user action
    user = User.objects.get(username=request.session.get("username"))
    for item in itemList:
        if item.id == productid:
            item_name = item.itemname

templates/studentswap/product/buy.html
<!--This is the page the user comes to when he clicks the "buy" option in the navigation bar in the header.
    This is the page listing items which uses buy.css. -->
{% extends "studentswap/base.html" %}
{% load static %}

{% block csslinks %}
    <link rel="stylesheet" href="{% static "css/buy.css" %}">
     <link rel="stylesheet" href="{% static "css/product.css" %}">
{% endblock %}

{% block jslinks %}
     <script src="{% static "js/jquery-3.7.1.min.js" %}"></script>
    <script src="{% static "js/scripts.js" %}"></script>
    <script src="{% static "js/searchresults.js" %}"></script>
{% endblock %}

{% block content %}

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
        {{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}

    <!--Item categories navigation bar-->
    <div class="itemcategories">
         <a class="categories" href="{% url "buyitem" %}?category=Furniture" ><b>Furniture</b></a>
        <a class="categories" href="{% url "buyitem" %}?category=Electronic devices" ><b>Electronic devices</b></a>
        <a class="categories" href="{% url "buyitem" %}?category=Books" ><b>Books</b></a>
         <a class="categories" href="{% url "buyitem" %}?category=Kitchenware" ><b>Kitchenware</b></a>
        <a class="categories" href="{% url "buyitem" %}?category=Home Accessories" ><b>Home accessories</b></a>
         <a class="categories" href="{% url "buyitem" %}?category=Other" ><b>Miscellaneous</b></a>
    </div>


   <div id="hamburgermenu"><i class="fa-solid fa-bars"></i></div>

<div class="maincontent">

      <!--Filters section of the page- Subcategory,Price, Popularity, Sort by date-->
  <div class="filters">

   <form id="filterForm" method="GET" action="{%  url "filtered" %}">

    <div class="filter" id="categories">
        <p><b>Category</b></p>
                <div class="option">

            <input type="radio" id="living" name="category" value="Furniture" data-category="Furniture" data-ajax-url="{% url "get_subcategories" %}" >
              <label for="category">Furniture</label>
        </div>
       <div class="option">
        <input type="radio" id="dining" name="category" value="Electronic devices" data-category="Electronic devices" data-ajax-url="{% url "get_subcategories" %}">
          <label for="category">Electronic devices</label>
       </div>
       <div class="option">
        <input type="radio" id="bedroom" name="category" value="Books" data-category="Books" data-ajax-url="{% url "get_subcategories" %}">
          <label for="category">Books</label>
       </div>
       <div class="option">
        <input type="radio" id="homeoffice" name="category" value="Kitchenware" data-category="Kitchenware" data-ajax-url="{% url "get_subcategories" %}">
          <label for="category">Kitchenware</label>
       </div>
       <div class="option">
        <input type="radio" id="subother" name="category" value="Home Accessories" data-category="Home Accessories" data-ajax-url="{% url "get_subcategories" %}">
          <label for="category">Home Accessories</label>
       </div>
        <div class="option">
        <input type="radio" id="subother" name="category" value="Other" data-category="Miscellaneous" data-ajax-url="{% url "get_subcategories" %}">
          <label for="category">Miscellaneous</label>
       </div>
</div>
{#    </div>#}

    <div class="filter" id="subcategories">
        <p><b>Subcategory</b></p>
                <div class="option">
            <input type="radio" id="living" name="subcategory" value="">
              <label for="subcategory">Living Room Furniture</label>
        </div>
       <div class="option">
        <input type="radio" id="dining" name="subcategory" value="">
          <label for="subcategory">Dining Room Furniture</label>
       </div>
       <div class="option">
        <input type="radio" id="bedroom" name="subcategory" value="">
          <label for="subcategory">Bedroom Furniture</label>
       </div>
       <div class="option">
        <input type="radio" id="homeoffice" name="subcategory" value="">
          <label for="subcategory">Home Office Furniture</label>
       </div>
       <div class="option">
        <input type="radio" id="subother" name="subcategory" value="">
          <label for="subcategory">Other</label>

    </div>
    </div>

    <div class="filter">
        <p><b>Price</b></p>
        <div class="option">
            <input type="radio" id="price1" name="price" value="0.00-25.00">
              <label for="price1">Under $25</label>
        </div>
       <div class="option">
        <input type="radio" id="price2" name="price" value="25.00-50.00">
          <label for="price2">$25-$50</label>
       </div>
       <div class="option">
        <input type="radio" id="price3" name="price" value="50.00-100.00">
          <label for="price3">$50-$100</label>
       </div>
       <div class="option">
        <input type="radio" id="price4" name="price" value="100.00-1000.0">
          <label for="price4">Above $100</label>
       </div>
    </div>

{#popularity will be implemented later#}
{#    <div class="filter">#}
{#        <p><b>Popularity</b></p>#}
{#        <div class="option">#}
{#            <input type="radio" id="pop1" name="popularity" value="Pop1">#}
{#              <label for="pop1">Under 10</label>#}
{#        </div>#}
{#       <div class="option">#}
{#        <input type="radio" id="pop2" name="popularity" value="Pop2">#}
{#          <label for="pop2">10-50</label>#}
{#       </div>#}
{#       <div class="option">#}
{#        <input type="radio" id="pop3" name="popularity" value="Pop3">#}
{#          <label for="pop3">50-100</label>#}
{#       </div>#}
{#       <div class="option">#}
{#        <input type="radio" id="pop4" name="popularity" value="Pop4">#}
{#          <label for="pop4">Above 100</label>#}
{#       </div>#}
{#    </div>#}


    <div class="filter">
        <p><b>Sort by Date</b></p>
        <div class="option">
            <input type="radio" id="latest" name="date" value="Sort by Latest">
              <label for="latest">Sort by Latest</label>
        </div>
       <div class="option">
        <input type="radio" id="oldest" name="date" value="Sort by Oldest">
          <label for="oldest">Sort by Oldest</label>
       </div>
      
    </div>
    <button class="filterbtn">FILTER</button>
    
   </form>
 
   
   </div>


    <!--One big Itemscontainer that contains multiple items (like cards)-->

    <!-- Images taken from the following sources-
     These images are reused in other pages as well.
https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.wired.com%2Fgallery%2Fbest-office-chairs%2F&psig=AOvVaw3xV1G9_3ApcUuRMabykbh3&ust=1694891414713000&source=images&cd=vfe&opi=89978449&ved=0CA8QjRxqFwoTCKDe09eorYEDFQAAAAAdAAAAABBL
https://www.google.com/search?q=bedframe&tbm=isch&ved=2ahUKEwjJnpDTqa2BAxXYK2IAHRPbCw4Q2-cCegQIABAA&oq=bedframe&gs_lcp=CgNpbWcQAzIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQ6BAgjECc6BwgAEIoFEEM6BwgjEOoCECc6CAgAEIAEELEDOgoIABCKBRCxAxBDOgQIABADUMIIWMKvAmD_sgJoA3AAeACAAXaIAfkEkgEDOC4xmAEAoAEBqgELZ3dzLXdpei1pbWewAQrAAQE&sclient=img&ei=G60EZYmlC9jXiLMPk7avcA&authuser=0&bih=878&biw=1504&hl=en#vhid=a56PbCBi2XUc5M&vssid=3981:9gDH_xaTErE03M
https://media.karousell.com/media/photos/products/2021/10/9/queen_size_mattress_1633766564_220ace55_progressive.jpg-->
    <div class="outercontainer">
{#    <div class="results"></div>#}

  <div class="itemscontainer">
     {#  if there are items to show#}
      {% if productlist %}

      {% for product in productlist %}
            <div class="item">

        <div class="imgclass">
            <img src="{% static product.imageurl %}" alt="{{ product.imagealt }}">
        </div>

        <div class="info">
         <div class="iteminfo">
            <div class="rating">
                <p class="itemtext">{{ product.itemname}}</p>

                {#the heart icon for adding an item to wishlist is only available if the user is logged in#}
                {% if  request.session.username %}
{#                <a href="{% url "users:wishlist" product.id request.session.username  %}" onclick="addedalert()"><i class="fa-solid fa-heart itemtext"></i></a>#}
                {% endif %}
            </div>

            <p class="itemtext">${{ product.price }}</p>
           <div class="info-delete">
            <a href="{% url "product_detail" product.id %}" class="itemtext">More info</a>
             {% if request.session.username == "Admin" %}
             <a href="{% url "deleteconfirmation" product.id %}" style="background-color: rgb(242, 106, 106); padding:0.4em"><i class="fa-solid fa-trash"></i></a>
             {% endif %}
         </div>
         </div>

        </div>

    </div>

      {% endfor %}
      {% else %}
     <p id="error_msg">Sorry, no items to show!</p>
      {%  endif %}

    </div>

</div>

  </div>

    <script>
     function addedalert()
     {
         alert("Item added to your wishlist!");
     }
    </script>

   {% endblock %}

templates/studentswap/product/deleteconfirmation.html
{% extends "studentswap/base.html" %}
{% load static %}

{% block csslinks %}
    <link rel="stylesheet" href="{% static "css/deleteconfirmation.css" %}">
{% endblock %}


{% block content %}
    <div class="deletebox">
    <div><h2>Are you sure you want to delete ?</h2></div>
     <div>

     <form method="POST">
        {% csrf_token %}
         <div class="deletefields" ><a href="{% url "delete" productid %}" style="background-color: indianred">Yes,delete</a></div>
         <div class="deletefields"> <a href="{% url "buy" %}">Cancel</a></div>

     </form>
    </div>
    </div>
{% endblock %}

templates/studentswap/product/homepagefeed.html
 <!--This is the HTML for the home page when the user is logged in-->
{% extends "studentswap/base.html" %}
{% load static %}

{% block csslinks %}
    <link rel="stylesheet" href="{% static "css/home-alt.css" %}">
    <link rel="stylesheet" href="{% static "css/buy.css" %}">
{% endblock %}

{% block content %}

    <div class="main">

{#    container for recent activity of the user#}
        <div class="listcontainer">
         <h2 style="color: var(--primary-color2)">Here's whats happening around !</h2><br>
            <div class="viewed">

                <h3>Let's get you upto speed</h3></div>

            <div class="list">
                 <div class="activityhome">

                    {% for action in actions %}

                        <div> ► <a id="activitylinks" href="{% url "users:profile_detail" action.user.username %}"><span style="color:var(--primary-color3)">{{ action.user.username }}</span></a>
                            {{ action.verb }} <a id="activitylinks" href="{{ action.target.get_absolute_url }}">
                            <span style="color:var(--primary-color3)">{{ action.target }}</span></a> on {{ action.created }}</div>

                     {% empty %}

                    <div>No activity yet.</div>

                         {% endfor %}

                 </div>
            </div>
            </div>
        </div>


{% endblock %}

templates/studentswap/product/product.html
 <!--This is the HTML for the product details page-->
{% extends "studentswap/base.html" %}
{% load static %}

{% block csslinks %}
<link rel="stylesheet" href="{% static "css/product.css" %}">
{#    <link rel="stylesheet" href="{% static "css/global.css" %}">#}
{% endblock %}


{% block jslinks %}
     <script src="{% static "js/jquery-3.7.1.min.js" %}"></script>
    <script src="{% static "js/scripts.js" %}"></script>
    <script src="{% static "js/searchresults.js" %}"></script>
{% endblock %}

{% block content %}
     <!-- Product page that shows details of a specific product-->
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
        {{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}


    <div class="product">
        <div class="productimage">
            <img class="productimg" src="{% static item.imageurl %}" alt="{{item.imagealt}}">
        </div>
        <div class="productinfo">
            <div class="maininfo">
                <div>
                <h2> {{ item.itemname }}</h2>
                <h3>US ${{ item.price }}</h3>
                <p class="secondaryinfo">Description : {{ item.description}} </p>
                    <br>
                </div>
                <div >
                    <p class="secondaryinfo">Posted by : <a style="background-color:white; font-weight: bold; !important;" href="{% url "users:profile_detail" item.user.username %}"> {{ item.user.username }}</a></p>
                <p class="secondaryinfo">Date posted : {{ item.date_posted }}</p>
                    </div>
            </div>

             <div class="secondaryinfo">
                <p>Category : {{ item.category }}</p>
                <p>Subcategory : {{ item.subcategory}}</p>
             </div>
            <div class="productbuttons">
{#                <button id="addtowishlist" class="prodbtn">Add to Wishlist</button>#}
                <button class="prodbtn" onclick=window.location.href="{% url "edit" item.id %}" >Edit item</button>
                <button class="prodbtn">Buy</button>
            </div>
            

                {% csrf_token %}
                <p class="secondaryinfo">Comments</p>
                <div class="pastcomments">

                    {% for comment in comments %}
                    <div class="individualcommentbox" id="comment-{{ comment.id }}">
                        <p id="commentauthor"> @ <a href="{% url "users:profile_detail" comment.user.username %}">{{ comment.user.username }}</a>  •  {{ comment.datecommented }}</p>
                            <p id="commentbyauthor">   {{ comment.comment }}</p>

                        {% if request.session.username == comment.user.username or request.session.role == "admin" %}
                            <div class="commentbuttonbox">
                            <button class="commentbuttons edit-comment" id="editcommentbutton"  data-editcomment-id="{{ comment.id }}">Edit</button>
                             <button class="commentbuttons delete-comment" id="deletecomment" data-deletecomment-url="{% url "deletecomment" comment.id %}" data-comment-id="{{ comment.id }}">Delete</button>

                            </div>

                             <form class="editcomment" id="editcomment-{{ comment.id }}"  style="display: none;">
                      <input type="text" value="{{comment.comment}} " id="editcommentbox-{{ comment.id }}">
                     <button class="commentbuttons savecomment" data-savecomment-url="{% url "savecomment" comment.id %}" data-savecomment-id="{{ comment.id }}">Save changes</button>
                  </form>

                        {% endif %}
                   </div>

                      {% empty %}
                        <br>
                        <p style="color:var(--primary-color4)">No comments yet</p>


                      {% endfor %}


                </div>
                 {% if request.session.username %}
                <form class="commentsection">
                <input type="text" placeholder=" Enter your comment here " id="commentbox" >
                <button class="commentbuttons" id="comment" data-comment-url="{% url "comment" item.id request.session.username %}"  data-productid="{{ item.id }}">Comment</button>

                 </form>




                 {% endif %}
        </div>
       
    </div>


{% endblock %}

templates/studentswap/product/searchresults.html
 <!--This is the HTML for the sell page-->

{% extends "studentswap/base.html" %}
{% load static %}

{% block csslinks %}

      <link rel="stylesheet" href="{% static "css/buy.css" %}">
     <link rel="stylesheet" href="{% static "css/searchresults.css" %}">
     <link rel="stylesheet" href="{% static "css/home-alt.css" %}">
{% endblock %}


{% block jslinks %}
     <script src="{% static "js/jquery-3.7.1.min.js" %}"></script>
{#    <script src="{% static "js/searchresults.js" %}"></script>#}
{% endblock %}


{% block content %}

<!--   Results handled in searchresults.js-->
     <div class="searchresults">
     <br><br>
         <div class="viewed"><h3>Search Results</h3></div>
              <div class="itemscontainer">
               {#  if there are items to show#}
                {% if productlist %}

                  {% for product in productlist %}
                   <div class="item">

                    <div class="imgclass">
                     <img src="{% static product.imageurl %}" alt="{{ product.imagealt }}">
                    </div>

                    <div class="info">
                     <div class="iteminfo">
                        <div class="rating">
                            <p class="itemtext">{{ product.itemname}}</p>
{#                            <a href="{% url "wishlist" product.id %}"><i class="fa-solid fa-heart itemtext"></i></a>#}
                        </div>

                        <p class="itemtext">${{ product.price }}</p>
                          <div class="info-delete">
                        <a href="{% url "product_detail" product.id %}" class="itemtext">More info</a>

                          </div>
                     </div>

                    </div>

                    </div>
                 {% endfor %}

                    {% else %}
                    <p>Sorry, no items to show for your search! Try again</p>
                  {%  endif %}



               </div>
              </div>



</div>

 {% endblock %}