cs5774b/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('studentswap/', include('studentswap.urls')),
    path('users/', include('users.urls')),


]

studentswap/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [

    path('home/', views.home, name='home'),
    path('buy/items/<int:productid>/', views.productinfo, name='product_detail'), #product detail
    path('buy/items/', views.buyitem, name="buyitem"), #listitemsbycategory
    path('buy/items/all/', views.buy, name="buy"), #listallitems
    path('sell/', views.sell, name="sell"),  #addingitem
    path('searchresults/', views.searchresults, name="searchresults"),
    path('deleteconfirmation/<int:productid>/',views.deleteconfirmation,name="deleteconfirmation"),  #delete confirmation
    path('deleteitem/<int:productid>/',views.delete,name="delete"),   #actual deletion
    path('edititem/<int:productid>/',views.edit,name="edit"),#requesting edit form
    path('editingitem/<int:productid>/',views.savechanges,name="saveedit"),   #saving edited changes
    path('getsubcategories/', views.getsubcategories ,name='get_subcategories'),
    path('filter/', views.filter, name='filtered'),
    path('comment/<int:productid>/<str:username>/', views.addcomment, name='comment'), #add comment
    path('deletecomment/<int:commentid>/', views.deletecomment, name='deletecomment'),  # delete comment
    path('savecomment/<int:commentid>/', views.savecomment, name='savecomment'),  #editing and updating comment


]

users/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='users'

urlpatterns = [

    # path('home/', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('profile/<str:username>', views.profile, name='profile_detail'),  # profile detail
    path('editprofile/<str:username>', views.editprofile, name='profile_edit'),  # get edit form for editing profile details
    path('saveprofile/<str:username>', views.saveprofile, name='saveprofilechanges'),  # saving profile edit details
    path('loggedin/', views.login_user, name="login"),  # login
    path('logout/', views.logout_user, name="logout"),  # logout
    path('wishlist/delete/<int:productid>/', views.wishlistdelete, name="wishlistdelete"),
    path('dashboard/<str:username>', views.dashboard, name="dashboard"),  # user dashboard
    path('home/feed', views.homeactivityfeed, name='homefeed'), #home page showing activity feed for logged in users
    path('wishlist/<int:productid>/<str:username>',views.wishlist, name="wishlist"), #to add item to wishlist
    path('wishlist/<str:username>',views.wishlistpage, name="wishlistpage"),  #to go to wishlist page

]

studentswap/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.


class Item(models.Model):
    itemname=models.CharField(max_length=200)
    price=models.DecimalField(max_digits=10, decimal_places=2)
    description=models.TextField()
    category=models.CharField(max_length=40)
    subcategory=models.CharField(max_length=40)
    imageurl=models.CharField(max_length=200)
    imagealt= models.CharField(max_length=200)
    date_posted=models.DateTimeField(auto_now_add=True)
    # boolean value to keep a track of the user's listings
    is_sold = models.BooleanField(default=False)
    user=models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.itemname

    def get_absolute_url(self):
        return reverse('product_detail', args=[self.id])


# user login data
# regular_user={"username":"Mahita", "password": "regular"}
# admin_user={"username":"Admin", "password": "admin@23"}

studentswap/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from .models import Item, User
from actions.models import Action
from comments.models import Comment
from django.http import JsonResponse
from django.db.models import Q
from django.http import HttpResponse


import random

# Create your views here.

# home view
def home(request):
    return render(request, "studentswap/index.html")

def buy(request):
    itemList = Item.objects.all().order_by('-date_posted')
    return render(request, "studentswap/product/buy.html", {"productlist": itemList})


#list view
def buyitem(request):
    itemList=Item.objects.all().order_by('-date_posted')
    listbycategory=[]
    itemcategory=request.GET.get('category', None)
    if itemcategory is not None:
        for item in itemList:
            if item.category.strip() == itemcategory.strip():
                listbycategory.append(item)
        return render(request, "studentswap/product/buy.html", {"productlist": listbycategory})
    else:
        return render(request, "studentswap/product/buy.html", {"productlist": itemList})



#add view- form to fill in details
def sell(request):
    if request.method=="POST":
        category, subcategory = request.POST.get('subcategoryfilters').split("-")
        name = request.POST.get('itemname')
        price = request.POST.get('price')
        desc = request.POST.get('desc')
        category = category
        subcategory = subcategory
        is_listing=True
        user=User.objects.get(username=request.session.get("username"))

        # assigning default images to categories,subcategories as the application right now doesn't have scope for the user to upload their pictures.
        # all pictures taken from unsplash.com
        if category=="Furniture" :
            if subcategory=='Living Room Furniture':
                imageurl="images/furniture/phillip-goldsberry-fZuleEfeA1Q-unsplash.jpg"
            elif subcategory=='Dining Room Furniture':
                imageurl="images/furniture/samantha-gades-XDaa1RPb6n8-unsplash.jpg"
            elif subcategory=='Bedroom Furniture':
                imageurl="images/furniture/christopher-jolly-GqbU78bdJFM-unsplash.jpg"
            elif subcategory=='Home Office Furniture':
                imageurl="images/furniture/gian-paolo-aliatis-6AWuKs10_M4-unsplash.jpg"
            elif subcategory=='Other':
                imageurl="images/furniture/di_an_h-g_8MrEZAvyE-unsplash.jpg"

        elif category=="Electronic devices":
            if subcategory=='Computer & Accessories':
                imageurl="images/electronic-devices/clement-helardot-95YRwf6CNw8-unsplash.jpg"
            elif subcategory=='Mobile devices & Accessories':
                imageurl="/images/electronic-devices/charlesdeluvio-GXNo-OJynTQ-unsplash.jpg"
            elif subcategory=='Home Appliances':
                imageurl="images/electronic-devices/louis-hansel-ktVKZRYUP4Y-unsplash.jpg"
            elif subcategory=='Audio & Music':
                imageurl="images/electronic-devices/caleb-woods-VVuRLhyTmXM-unsplash.jpg"
            elif subcategory=='Other':
                imageurl="images/electronic-devices/photo-1496181133206-80ce9b88a853.avif"

        elif category=="Home Accessories":
            if subcategory=='Lighting':
                imageurl="images/home accessories/sincerely-media-VDPauwJ_sHo-unsplash.jpg"
            elif subcategory=='Bedding & Linens':
                imageurl="images/home accessories/susan-wilkinson-9I4gTSe3_Po-unsplash.jpg"
            elif subcategory=='Bathroom Accessories':
                imageurl="images/home accessories/curology-cI_LU-uAkcE-unsplash.jpg"
            elif subcategory=='Kitchen Accessories':
                imageurl="images/home accessories/annie-spratt-QOBHnWEg-mk-unsplash.jpg"
            elif subcategory == 'Desk Accessories':
                imageurl = "images/home accessories/freddie-marriage-vSchPA-YA_A-unsplash.jpg"

            elif subcategory=='Other':
                imageurl="images/home accessories/patrick-tomasso-1NTFSnV-KLs-unsplash.jpg"

        elif category == "Books":
            if subcategory=='Textbooks':
                imageurl = "images/books/Structure-and-Interpretation.jpg"
            elif subcategory == 'Notebooks':
                    imageurl = "images/books/Structure-and-Interpretation.jpg"
            elif subcategory == 'Study guides':
                    imageurl = "images/books/Structure-and-Interpretation.jpg"
            elif subcategory == 'Interview Prep':
                    imageurl = "images/books/Structure-and-Interpretation.jpg"
            elif subcategory == 'Other':
                    imageurl = "images/books/Structure-and-Interpretation.jpg"

        elif category == "Kitchenware":
            if subcategory=='Cookware':
                imageurl="images/kitchenware/cooker-king-AOVtEuU9UGc-unsplash.jpg"
            elif subcategory=='Cutlery':
                imageurl="images/kitchenware/anna-kumpan-e8SpIvBceJw-unsplash.jpg"
            elif subcategory=='Kitchen Tools & Utensils':
                imageurl="images/kitchenware/becca-tapert-A_L2xNKgENg-unsplash.jpg"
            elif subcategory=='Kitchen Appliances':
                imageurl="images/kitchenware/alexandre-boucey-IZF51fI0p5w-unsplash.jpg"
            elif subcategory=='Other':
                imageurl="images/kitchenware/cooker-king-zEgp30gYpKk-unsplash.jpg"

        else:
            imageurl='images/miscellaneous/daniel-norris-ZN_86cZrSN0-unsplash.jpg'


        newitem = Item(itemname=name, price=price, description=desc, category=category, subcategory=subcategory,imageurl=imageurl,imagealt=name,user=user,is_sold=is_listing)
        newitem.save()
        #log the action
        action=Action(user=user, verb=f"sold an item -{name} ", target=newitem)
        action.save()
        messages.add_message(request, messages.SUCCESS, "You successfully sold the item %s !" % newitem.itemname)
        return redirect("product_detail", productid=newitem.id)
    else:
        return render(request, "studentswap/product/sell.html",)


# displaying search results based on sample keywords entered by user
def searchresults(request):
    searchresultlist = []
    if request.method=='GET':
        keyword=request.GET.get('searchitems','')
        itemList = Item.objects.all().order_by('-date_posted')
        for item in itemList:
                    if (keyword in ["electronics","computers","devices"]) and item.category == "Electronic devices":
                        searchresultlist.append(item)
                    elif (keyword in ["furniture","bed","table"]) and item.category == "Furniture":
                        searchresultlist.append(item)
                    elif (keyword in ["books","textbooks"]) and item.category == "Books":
                        searchresultlist.append(item)
                    elif (keyword in ["kitchen","cutlery","utensils"]) and item.category == "Kitchenware":
                        searchresultlist.append(item)
                    elif (keyword in ["lights","desk accessories"]) and item.category == "Home Accessories":
                        searchresultlist.append(item)
        return render(request, "studentswap/product/searchresults.html", {"productlist": searchresultlist})



# detail view - if the user sees the product detail, add it to recently viewed list
def productinfo(request,productid):
    itemList = Item.objects.all().order_by('-date_posted')
    comments=Comment.objects.filter(item=productid).order_by('-datecommented')
    for item in itemList:
        if item.id==productid:
            item.save()
            break
    return render(request, "studentswap/product/product.html", {"item": item, 'comments':comments})


#
# # edit view- edit view renders the form where the user can make changes
def edit(request,productid):
    itemList = Item.objects.all()
    for item in itemList:
        if(productid==item.id):
            return render(request,"studentswap/product/editlisting.html",{"item": item})
#
#
#savechanges view actually saves the changes once the form is submitted
def savechanges(request,productid):
    itemList = Item.objects.all()
    category, subcategory = request.POST.get('subcategoryfilters').split("-")
    category = category
    subcategory = subcategory
    print( category, subcategory)
    #logging the user action
    user = User.objects.get(username=request.session.get("username"))


    for item in itemList:
        if(productid==item.id):

            if request.POST.get('desc')!=item.description:
                action = Action(user=user, verb=f"edited the item's description to '{ request.POST.get('desc')}'", target=item)
                action.save()
            item.itemname=request.POST.get('itemname')
            if request.POST.get('itemname')!=item.itemname:
                action = Action(user=user, verb=f"edited the item's name to '{request.POST.get('itemname')}'", target=item)
                action.save()
            item.description=request.POST.get('desc')
            item.price=request.POST.get('price')
            item.category=category
            item.subcategory=subcategory
            item.save()
            break
    messages.add_message(request, messages.INFO, "You successfully edited the item %s !" % item.itemname) #success msg
    return redirect("product_detail", productid=item.id)


# delete views- for confirming the deletion and actually deleting it
def deleteconfirmation(request,productid):
    return render(request, "studentswap/product/deleteconfirmation.html",{"productid":productid})

# search for the item using it's id and delete it from the database
def delete(request,productid):
    itemList = Item.objects.all()
    # logging the user action
    user = User.objects.get(username=request.session.get("username"))
    for item in itemList:
        if item.id == productid:
            item_name = item.itemname

templates/studentswap/base.html
 <!--This is the HTML for the sell page-->
{% load static %}
 <!DOCTYPE html>
 <html lang="en">
 <head>
     <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">

   <link rel="stylesheet" href="{% static "css/global.css" %}">
     <link rel="stylesheet" href="{% static "css/header.css" %}">
     <link rel="stylesheet" href="{% static "css/footer.css" %}">

     {% block csslinks %}
     {% endblock %}

      <script src="{% static "js/jquery-3.7.1.min.js" %}"></script>
{#      <script src="{% static "js/searchresults.js" %}"></script>#}
{#  <script src="{% static "js/scripts.js}" %}"></script>#}

 {% block jslinks %}
 {% endblock %}


   <link
   href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
   rel="stylesheet"
 >
 <link rel="preconnect" href="https://fonts.googleapis.com">
 <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
 <link href="https://fonts.googleapis.com/css2?family=Indie+Flower&display=swap" rel="stylesheet">
     <title>StudentSwap</title>
 </head>

 <body>

   <!--Header section-->
     <header>

         <div class="logo">
             {% if  request.session.username %}
           <a href="{% url "users:homefeed" %}"><img src="{% static "images/logo.png" %}" alt="logo"></a>
           <a href="{% url "users:homefeed" %}">$tudent$wap</a>
                 {% else %}
           <a href="{% url "home" %}"><img src="{% static "images/logo.png" %}" alt="logo"></a>
           <a href="{% url "home" %}">$tudent$wap</a>
             {% endif %}
         </div>


         <div class="searchbar">
            <form id="searchform" method="GET" action="{% url "searchresults" %}">
                {% csrf_token %}
            <input  class="searcharea" id="searchkey" type="text" name="searchitems" placeholder="Search electronics, computers,devices etc" >
{#             <input type="submit" name="submitsearch" class="searchbutton" value="Search" data-searchurl="{% url "searchresults" %}">#}
                <button class="searchbutton" >Search</button>

            </form>

        </div>

         <div class="navigation">
             <a href="{% url "buy" %}"><b>Buy</b></a>
{#           sell and wishlist pages are only available if the user is logged in#}
            {% if  request.session.username %}
             <a href="{% url "sell" %}"><b>Sell</b></a>
{#             <a href="{% url "users:wishlistpage" request.session.username %}"><b>Wishlist</b></a>#}
                <a href="{% url "users:dashboard" request.session.username %}"><b>Dashboard</b></a>
            {% endif %}
             <div class="loginform">

                 {% if  request.session.username %}
                     <form id="login">
                     <p>Logged in as<a style="color: var(--primary-color3) ! important;" href="{% url "users:profile_detail" request.session.username %}">{{ request.session.username }}</a></p>
                     <a href="{% url "users:logout" %}"><b>Logout</b></a>
                 </form>


             {% else %}
                     <form id="login" action="{% url "users:login" %}" method="POST">
                 {% csrf_token %}
                 <div class="loginfields">
                     <form>
                <div ><input  type="text" placeholder="Enter username" name="username"></div>
                <div ><input type="password" placeholder="Enter password" name="password"></div>
                <div><input type="submit" value="Login" class="loginbutton">  or<a href="{% url "users:register" %}">Register</a></div>
                     </form>
                 </div>

             </form>


             {% endif %}
                 </div>


         </div>

     </header>

{#   main content of the page#}

    {% block content %}
   {% endblock %}


      <!--Footer section-->

     <footer>
         <div class="links">
             <a href="#"><b>About</b></a>
             <a href="#"><b>Contact</b></a>
             <a href="#"><b>Directions</b> </a>

             <div class="copyright">
                 <i class="fa-regular fa-copyright"></i>
             <p><b>2023 StudentSwap</b></p>
             </div>
           </div>



         <div class="social-media-icons">
             <a class="button"><i class="fa-brands fa-facebook"></i></a>
             <a class="button"><i class="fa-brands fa-instagram"></i></a>
         </div>
     </footer>

 </body>
 </html>

templates/studentswap/index.html
{% extends "studentswap/base.html" %}
{% load static %}

{% block csslinks %}
<link rel="stylesheet" href="{% static "css/index.css" %}">
{#    <link rel="stylesheet" href="{% static "css/global.css" %}">#}
{% endblock %}


{% block jslinks %}
{#     <script src="{% static "js/jquery-3.7.1.min.js" %}"></script>#}
{#    <script src="{% static "js/scripts.js" %}"></script>#}
{% endblock %}

{% block content %}
  <!-- images taken from https://blush.design/
        https://blush.design/collections/aJPO7jxl3W0C01VALXfW/hands/hands-phone/pK9um52QGfTfh10N?c=Skin_0%7Efcb7a0
    https://blush.design/collections/aJPO7jxl3W0C01VALXfW/hands/vertical-scenes-exchange-colors/0zKHgHAg8H3Kn1Sx?c=Skin_0%7Efbd2ae-0.1%7E564634-0.2%7Efbd2ae -->
    {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
        {{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}

    <main>
<div class="introduction">
    <div class="intro">
      <h3><b>Welcome to StudentSwap, Hokies! </b></h3><br>
      <p>The one-stop marketplace to navigate the world of student essentials!</p>
      <p id="slogan">Save, Sustain and Stress less.</p><br>
      <a href="{%  url "home" %}" class="introbtn"><b>Sign Up or Login</b></a>
    </div>
</div>


<div class="working-buyer">
    <div class="intro">
        <h3><b> As a BUYER </b></h3><br>
        <p>Starting your academic adventure and looking for affordable items?</p><br>
        <a href="{%  url "buy" %}" class="introbtn"><b>BUY NOW!</b></a>
      </div>
    <div class="introimg">
        <img src="{% static "images/handsphone.png" %}" alt="hand holding phone">
    </div>

</div>
<div class="working-seller">
    <div class="introimg">
        <img src="{% static "images/handsbuying.png" %}" alt="two hands exchanging money and item">
    </div>
    <div class="intro">
        <h3><b> As a SELLER </b></h3><br>
      <p>Have items that you're no longer using? <br>Turn your clutter into cash.</p><br>
      <a href="{%  url "home" %}" class="introbtn" id="sell_home" onclick="asklogin()"><b>SELL NOW!</b></a>
    </div>
</div>

{#if the user clicks on sell button without logging in, send an alert asking them to login #}
<script>
    function asklogin()
    {
        alert("Please login first!");
    }
</script>

<br>
    </main>
{% endblock %}