cs5774b/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('studentswap/', include('studentswap.urls')),
    path('users/', include('users.urls')),


]

users/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='users'

urlpatterns = [

    # path('home/', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('profile/<str:username>', views.profile, name='profile_detail'),  # profile detail
    path('editprofile/<str:username>', views.editprofile, name='profile_edit'),  # get edit form for editing profile details
    path('saveprofile/<str:username>', views.saveprofile, name='saveprofilechanges'),  # saving profile edit details
    path('loggedin/', views.login_user, name="login"),  # login
    path('logout/', views.logout_user, name="logout"),  # logout
    path('wishlist/delete/<int:productid>/', views.wishlistdelete, name="wishlistdelete"),
    path('dashboard/<str:username>', views.dashboard, name="dashboard"),  # user dashboard
    path('home/feed', views.homeactivityfeed, name='homefeed'), #home page showing activity feed for logged in users
    path('wishlist/<int:productid>/<str:username>',views.wishlist, name="wishlist"), #to add item to wishlist
    path('wishlist/<str:username>',views.wishlistpage, name="wishlistpage"),  #to go to wishlist page

]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.


class Details(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    role = models.CharField(default="regular", max_length=50)
    campus = models.CharField(default="NVC")
    # boolean value to check if item is in the recently viewed list or not
    recently_viewed=models.BooleanField(default=False)

@receiver(post_save, sender=User)
def create_user_details(sender,instance,created, **kwargs):
    if created:
        Details.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_details(sender,instance, **kwargs):
    instance.details.save()

users/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib import messages
from django.contrib.auth.models import User
from .models import Details
from studentswap.models import Item
from actions.models import Action
from django.contrib.auth import authenticate
from django.http import HttpResponse
from comments.models import Comment

# Create your views here.

def register(request):
    if request.method=="POST":

        username = request.POST.get('username')
        firstname = request.POST.get('firstname')
        lastname = request.POST.get('lastname')
        email = request.POST.get('email')
        password = request.POST.get('password')
        campus=request.POST.get('incampus')
        user = User.objects.create_user(username, email, password, first_name=firstname,last_name=lastname)
        details,created=Details.objects.get_or_create(user=user)
        details.campus=campus
        details.save()
        # session variables
        request.session['username'] = user.username
        request.session['role'] = user.details.role
        messages.add_message(request, messages.INFO,
                             "You successfully registered with the username %s !" % user.username)  # success msg
        return redirect('users:profile_detail',username=username )
    else:
        return render(request, "users/user/register.html", )

def profile(request,username):
    user=get_object_or_404(User,username=username)
    return render(request, "users/user/profile.html",{"user": user} )

def editprofile(request,username):
    user = get_object_or_404(User, username=username)
    return render(request, "users/user/editprofile.html",{"user": user} )

def saveprofile(request,username):
    if request.method == "POST":
        u = User.objects.get(username=username)
        details=Details.objects.get(user=u)
        u.first_name = request.POST.get('firstname')
        u.last_name = request.POST.get('lastname')
        u.email = request.POST.get('email')
        newpassword=request.POST.get('password')
        if newpassword:
            u.set_password(newpassword)
            # log the action
        role=request.POST.get('role')
        if role:
            details.role=role
            details.save()
            action = Action(user=u, verb="'s role was changed by Admin. Click here to see -", target=u)
            action.save()
        details.campus=request.POST.get('incampus')
        u.save()
        details.save()
        return redirect('users:profile_detail',username=username)


# views for logging in and logging out for both regular and admin users
def login_user(request):
    username=request.POST.get("username")
    pwd=request.POST.get("password")

    user= authenticate(username=username, password=pwd)
    if user is not None:
        request.session['username'] = user.username
        request.session['role'] = user.details.role
        return redirect('users:profile_detail',username=username )
    else:
        # prompt the user if entered password or username are incorrect
        messages.add_message(request, messages.WARNING, "Incorrect password or username. Please try again" )
        return redirect('home')  # a landing page with welcome message will be shown if the user is not logged in



def logout_user(request):
    del request.session['username']
    del request.session['role']
    return redirect('home')


# adding item to wishlist
def wishlist(request,productid,username):
    comments = Comment.objects.all()
    u = User.objects.get(username=username)
    i = get_object_or_404(Item, pk=productid)
    for comment in comments:
        if comment.user == u.id and comment.item == i.id:
            comment.is_wishlist = True
            comment.save()
            break
    return HttpResponse(status=204)


#go to wishlist page and show all the items in wishlist
def wishlistpage(request,username):
    comments = Comment.objects.all()
    wishlist=[]
    for comment in comments:
        if comment.user.username == username and comment.is_wishlist==True:
            wishlist.append(comment)
    return render(request, "users/user/wishlist.html", {"productlist": wishlist})
#
# # dashboard view- where the user can edit  and delete (only admin) their listings
#shows recently viewed and mylistings


# to remove item from wishlist, change the boolean to false
def wishlistdelete(request,productid):
    itemList = Item.objects.all()
    for item in itemList:
        if item.id == productid:
            item.is_wishlist=False
            item.save()
            break
    messages.add_message(request, messages.WARNING, "You successfully deleted the item %s from wishlist!" % item.itemname)
    return redirect('users:wishlistpage')


def dashboard(request,username):
    user = User.objects.get(username=request.session.get("username"))
    actions=Action.objects.all()
    actionList = actions.filter(user = user).order_by('-created')
    itemlist=Item.objects.all().order_by('-date_posted')
    mylistings=[]
    recentlyviewed=[]
    for item in itemlist:
        if username == item.user.username:
            if item.is_sold:
                mylistings.append(item)
            # if item.recently_viewed:
            #     recentlyviewed.append(item)
    mylists= {"mylistings":mylistings,
              "recentlyviewed":recentlyviewed}
    return render(request, "users/user/dashboard.html", {"actions" : actionList, "mylistings":mylistings})
#

def homeactivityfeed(request):
    actions = Action.objects.all().order_by('-created')
    return render(request, "studentswap/product/homepagefeed.html",{"actions" : actions})

templates/users/user/dashboard.html
 <!--This is the HTML for the home page when the user is logged in-->
{% extends "studentswap/base.html" %}
{% load static %}

{% block csslinks %}
    <link rel="stylesheet" href="{% static "css/home-alt.css" %}">
    <link rel="stylesheet" href="{% static "css/buy.css" %}">
{% endblock %}

{% block jslinks %}
     <script src="{% static "js/jquery-3.7.1.min.js" %}"></script>
    <script src="{% static "js/scripts.js" %}"></script>
    <script src="{% static "js/searchresults.js" %}"></script>
{% endblock %}
{% block content %}

{#{%  include  "actions/action/feed.html" %}#}
    <div class="main">

{#    container for recent activity of the user#}
        <div class="listcontainer">
         <h2 style="color: var(--primary-color2)">Welcome to your dashboard, {{ request.session.username }}</h2><br>
            <div class="viewed">

                <h3>Your recent activity</h3></div>

            <div class="list">
                 <div class="activityhome">

                    {% for action in actions %}

                   <div> ► You {{ action.verb }} <a id="activitylinks" href="{{ action.target.get_absolute_url }}"><span style="color:var(--primary-color3)">{{ action.target }}</span></a> on {{ action.created }}</div>



                     {% empty %}

                    <div>No activity yet.</div>

                         {% endfor %}

                 </div>

            </div>
        </div>
        
{#        <div class="listcontainer">#}
{##}
{#            <div class="viewed">#}
{#                <h3>Recently viewed</h3></div>#}
{##}
{#            <div class="list">#}
{##}
{##}
{#                {% for product in recentlyviewed %}#}
{##}
{#                <div class="listitem">#}
{##}
{#                    <div class="listimg">#}
{#                        <img src="{% static product.imageurl %}" alt="{{ product.imagealt }}">#}
{#                    </div>#}
{##}
{#                    <div class="listinfo">#}
{##}
{#                            <p>{{ product.itemname}}</p>#}
{#                            <a href="{% url "product_detail" product.id %}" class="listbtn">More info</a>#}
{##}
{#                    </div>#}
{##}
{#                </div>#}
{##}
{#{% endfor %}#}
{##}
{#            </div>#}
{#        </div>#}

        <div class="listcontainer">
            <div class="viewed"><h3>Your listings</h3></div>

        <div class="itemscontainer" style="justify-content: flex-start;">



        {% for mlitem in mylistings %}
            <div class="item">

                <div class="imgclass">
                    <img src="{% static mlitem.imageurl %}" alt="{{ mlitem.imagealt }}">
                </div>
        
                <div class="info">
                 <div class="iteminfo">
                    <div class="rating">
                        <p class="itemtext">{{ mlitem.itemname}}</p>
                        <i class="fa-regular fa-heart"></i>
                    </div>
                    
                    <p class="itemtext">${{ mlitem.price }}</p>
                    <div class="listingbuttons">
                        {% if  request.session.username == mlitem.user.username  %}
                        <a href="{% url "edit" mlitem.id %}" >Edit listing</a>
                        <a href="{% url "deleteconfirmation" mlitem.id %}" ><i class="fa-solid fa-trash"></i></a>
                        {% endif %}
                    </div>
                 </div>

                </div>
            </div>
         {% endfor %}
        </div>
        </div>
         
        
            
        

            </div>
     </div>

{% endblock %}

templates/users/user/editprofile.html
 <!--This is the HTML for the product details page-->
{% extends "studentswap/base.html" %}
{% load static %}

{% block csslinks %}

    <link rel="stylesheet" href="{% static "css/profile.css" %}">
{% endblock %}


{% block content %}
     <!-- User profile page that shows the details of each user -->
    <ul class="messages">
       {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
          {{ message }}
        </li>
       {% endfor %}
    </ul>


    <div class="profile">
  {% if user.username == request.session.username %}
       <div class="profileintro">
{#           image taken from google images#}
           <img id="hokie" src="{% static "images/hokie.png" %}">
         <h3>Edit your profile, {{ user.username }}</h3>
       </div>
{% endif %}
        <form id="savechanges" method="POST" action="{%  url "users:saveprofilechanges" user.username %}">

            {% csrf_token %}

       <div class="profileuser">

         <div class="profile-field">
            <div class="fieldname" ><p>Username: </p></div>
             <div class="secondfield"><p>{{ user.username}}<span style="color: rgb(128,128,128); font-size:0.8rem;">&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
                 ** Username cannot be changed</span> </p> </div>

         </div>

         <div class="profile-field">
             <div class="fieldname"><label for="firstname">First name:</label> </div>
             <div class="secondfield"><input type="text" id="firstname" value="{{ user.first_name}}" name="firstname" required ></div>
         </div>

         <div class="profile-field">
             <div class="fieldname"><label for="lastname">Last name:</label> </div>
             <div class="secondfield" ><input type="text" id="lastname" value="{{ user.last_name}}" name="lastname" required></div>
         </div>


           <div class="profile-field">
             <div class="register-field campus">
                 <div ><label for="register-study">Which VT campus?</label></div>
                 <div class="radiooptions">
              <div>
                  <input type="radio" id="campus" name="incampus" value="NVC" {% if user.details.campus == "NVC" %}checked{% endif %}>
                  <label for="campus">NVC</label>
              </div>
                 <div >
                  <input type="radio" id="campus" name="incampus" value="Blacksburg" {% if user.details.campus == "Blacksburg" %}checked{% endif %}>
                    <label for="campus">Blacksburg</label>
              </div>
                     <div >
                  <input type="radio" id="campus" name="incampus" value="Arlington" {% if user.details.campus == "Arlington" %}checked{% endif %}>
                    <label for="campus">Arlington</label>
              </div>
                </div>
                     </div>
             </div>

         <div class="profile-field">
             <div class="fieldname"><label id="checkemail" for="email">Email: </label></div>
                <div class="secondfield"><input type="email" value="{{ user.email}}" id="email" name="email" required></div>
         </div>

         <div class="profile-field">
             <div class="fieldname"><label for="password">Enter your new Password: </label></div>
                <div class="secondfield"><input name="password" id="password"></div>
         </div>

        <div class="profile-field">
             {% if request.session.username == "admin" %}
             <div class="fieldname"><label for="role">Role: </label></div>
                <div class="secondfield"><input value="{{ user.details.role}}" id="role" name="role"></div>
            {% endif %}
         </div>

           <div class="profile-field">
               {% if user.username == request.session.username %}
               <button id="editbutton" >Save changes</button>
               {% elif request.session.role == "admin" %}
                 <button id="editbutton">Save changes</button>
               {% endif %}
           </div>



       </div>
      </form>

    </div>




{% endblock %}

templates/users/user/profile.html
 <!--This is the HTML for the product details page-->
{% extends "studentswap/base.html" %}
{% load static %}

{% block csslinks %}

    <link rel="stylesheet" href="{% static "css/profile.css" %}">
{% endblock %}

{% block content %}
     <!-- User profile page that shows the details of each user -->
    <ul class="messages">
       {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
          {{ message }}
        </li>
       {% endfor %}
    </ul>


    <div class="profile">
  {% if user.username == request.session.username %}
       <div class="profileintro">
{#           image taken from google images#}
           <img id="hokie" src="{% static "images/hokie.png" %}">
         <h3>Welcome to your profile, {{ user.username }}!</h3>
       </div>
    {% endif %}

       <div class="profileuser">

         <div class="profile-field">
             <div class="fieldname" ><p>Username: </p></div>
             <div class="secondfield"><p>{{ user.username}}</p></div>
         </div>

         <div class="profile-field">
             <div class="fieldname"><p>First name: </p></div>
             <div class="secondfield"><p>{{ user.first_name}}</p></div>
         </div>

         <div class="profile-field">
             <div class="fieldname"><p>Last name: </p></div>
             <div class="secondfield" ><p>{{ user.last_name}}</p></div>
         </div>

           <div class="profile-field">
                <div class="fieldname"><p>Campus: </p></div>
                <div class="secondfield"><p>{{ user.details.campus}}</p></div>
         </div>

         <div class="profile-field">
                <div class="fieldname"><p>Email: </p></div>
                <div class="secondfield"><p>{{ user.email}}</p></div>
         </div>


           <div class="profile-field">
                 <div class="fieldname" ><p>Role: </p></div>
               <div class="secondfield"><p>{{ user.details.role}}</p></div>
               {% if user.username == request.session.username or request.session.role == "admin" %}
               <button id="editbutton" onclick=window.location.href="{%  url "users:profile_edit" user.username %}">Edit profile</button>

               {% endif %}
           </div>
       </div>

    </div>


{% endblock %}

templates/users/user/register.html
 <!--This is the HTML for the sell page-->

{% extends "studentswap/base.html" %}
{% load static %}

{% block csslinks  %}
     <link rel="stylesheet" href="{% static "css/register.css" %}">
{% endblock %}

{% block jslinks %}
    <script src="{% static "js/jquery-3.7.1.min.js" %}"></script>
    <script src="{% static "js/usersscripts.js" %}"></script>
{% endblock %}

{% block content %}

      <!--Main section of the page that displays a form for the user to register-->

     <div class="registration">
       <div id="register-heading">
         <h3>User registration</h3>
       </div>

       <div class="registeruser">

         <form id="registerform" method="POST" action="{% url "users:register" %}">
              {% csrf_token %}
         <div class="register-field">
             <div ><label for="register-username">Enter username</label></div>
             <div ><input id="register-username" type="text" name="username" ><br></div>
         </div>

{##}
         <div class="register-field">
             <div ><label for="register-firstname">Enter firstname</label></div>
             <div ><input id="register-firstname" type="text" name="firstname" ><br></div>
         </div>


         <div class="register-field">
             <div ><label for="register-lastname">Enter lastname&nbsp</label></div>
             <div ><input id="register-lastname" type="text" name="lastname" ><br></div>
         </div>


             <div class="register-field campus">
                 <div ><label for="register-study">Which VT campus?</label></div>
                 <div class="radiooptions">
              <div>
                  <input type="radio" id="campus" name="incampus" value="NVC">
                  <label for="campus">NVC</label>
              </div>
                 <div >
                  <input type="radio" id="campus" name="incampus" value="Blacksburg">
                    <label for="campus">Blacksburg</label>
              </div>
                     <div >
                  <input type="radio" id="campus" name="incampus" value="Arlington">
                    <label for="campus">Arlington</label>
              </div>

                     </div>
             </div>

         <div class="register-field">
             <div ><label for="register-email">Enter email &nbsp&nbsp&nbsp&nbsp&nbsp</label></div>
             <div><input id="register-email" name="email" type="email" ><br></div>
         </div>

             <div class="register-field">
                 <div class="divlabel"><label for="register-password" >Enter password</label></div>
                 <div class="divinput"> <input type="password" name="password" id="register-password" ></div>

             </div>

             <div class="register-field">
                 <button type="submit" class="registerbtn">REGISTER</button><br>

             </div>




         </form>

     </div>

     </div>



{% endblock %}

templates/users/user/wishlist.html
 <!--This is the HTML for the home page when the user is logged in-->
{% extends "studentswap/base.html" %}
{% load static %}

{% block csslinks %}
      <link rel="stylesheet" href="{% static "css/wishlist.css" %}">
      <link rel="stylesheet" href="{% static "css/buy.css" %}">
    <link rel="stylesheet" href="{% static "css/home-alt.css" %}">
{% endblock %}


{% block jslinks %}
     <script src="{% static "js/jquery-3.7.1.min.js" %}"></script>
    <script src="{% static "js/searchresults.js" %}"></script>
{% endblock %}

{% block content %}
 {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
        {{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}
   <div class="main">
    <div class="wishlistcontainer">
        <div class="viewed"><h3>Here are the items saved by you!</h3></div>
    <div class="itemscontainer" style="justify-content: flex-start;">

        {% if productlist %}
      {% for product in productlist %}
            <div class="item">

        <div class="imgclass">
            <img src="{% static product.imageurl %}" alt="{{ product.imagealt }}">
        </div>

        <div class="info">
         <div class="iteminfo">
            <div class="rating">
                <p class="itemtext">{{ product.itemname}}</p>
            </div>

            <p class="itemtext">${{ product.price }}</p>
         <div class="info-delete">
            <a href="{% url "product_detail" product.id %}" class="itemtext">More info</a>
             <a href="{% url "users:wishlistdelete" product.id %}" style="background-color: rgb(242, 106, 106); padding:0.4em"><i class="fa-solid fa-trash"></i></a>

         </div>
         </div>

        </div>

     </div>

      {% endfor %}
      {% else %}
     <p id="error_msg">Sorry, no items in your wishlist!</p>
      {%  endif %}

       
       
    </div>
     
    
        
    
    
        </div>
 

   </div>
   
    
 
 
 
{% endblock %}